name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World! This is a GitHub Actions test."

      - name: Print Current Date and Time
        run: echo "The current date and time is: $(date)"